"""ORM models. Importing this package registers all tables on Base.metadata."""
from app.models.enums import (
    UserRole,
    JobStatus,
    PrimerType,
    ControlKind,
    FastqSource,
    ResultKind,
    KitStatus,
    Sex,
    ProjectRole,
    ConsensusSource,
    MatchTier,
    MatchCode,
    RunStatus,
    MismatchMetric,
    MatchingMode,
)
from app.models.user import User
from app.models.kit import (
    Kit,
    Primer,
    TagColumn,
    Control,
    PrimerPanel,
    TagLayout,
    kit_access,
)
from app.models.job import Job, SampleBatch, ResultFile
from app.models.project import (
    Project,
    Population,
    Study,
    SampleType,
    project_access,
    study_kits,
)
from app.models.sample import Sample, ReplicateObservation, ReplicateAmplification
from app.models.consensus import ConsensusGenotype, ConsensusEditLog, ReferenceAllele
from app.models.matching import (
    PopulationMarker,
    PopulationAlleleFrequency,
    MatchingSettings,
    MatchingRun,
    MatchSubgroup,
    MatchSupergroup,
    match_supergroup_members,
    Match,
    MatchingLog,
    AnimalOverride,
)

__all__ = [
    "UserRole",
    "JobStatus",
    "PrimerType",
    "ControlKind",
    "FastqSource",
    "ResultKind",
    "KitStatus",
    "Sex",
    "ProjectRole",
    "ConsensusSource",
    "MatchTier",
    "MatchCode",
    "RunStatus",
    "MismatchMetric",
    "MatchingMode",
    "User",
    "Kit",
    "Primer",
    "TagColumn",
    "Control",
    "PrimerPanel",
    "TagLayout",
    "kit_access",
    "Job",
    "SampleBatch",
    "ResultFile",
    "Project",
    "Population",
    "Study",
    "SampleType",
    "project_access",
    "study_kits",
    "Sample",
    "ReplicateObservation",
    "ReplicateAmplification",
    "ConsensusGenotype",
    "ConsensusEditLog",
    "ReferenceAllele",
    "PopulationMarker",
    "PopulationAlleleFrequency",
    "MatchingSettings",
    "MatchingRun",
    "MatchSubgroup",
    "MatchSupergroup",
    "match_supergroup_members",
    "Match",
    "MatchingLog",
    "AnimalOverride",
]
