"""baseline

Revision ID: 3092300d6a45
Revises: 
Create Date: 2026-07-14 19:09:14.162808
"""
from alembic import op
import sqlalchemy as sa


revision = '3092300d6a45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primer_panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('species_common', sa.String(length=128), nullable=True),
    sa.Column('species_latin', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('primers_csv_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primer_panels_code'), 'primer_panels', ['code'], unique=True)
    op.create_table('tag_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tags_csv_key', sa.String(length=512), nullable=True),
    sa.Column('column_names', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('organisation', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_code', sa.String(length=64), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('sent', 'received', 'analysed', 'reanalyse', name='kit_status'), nullable=False),
    sa.Column('primers_csv_key', sa.String(length=512), nullable=True),
    sa.Column('tags_csv_key', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['primer_panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_kit_code'), 'kits', ['kit_code'], unique=True)
    op.create_table('primers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('locus', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('microsat', 'snp', name='primer_type'), nullable=False),
    sa.Column('primer_f', sa.String(length=512), nullable=True),
    sa.Column('primer_r', sa.String(length=512), nullable=True),
    sa.Column('motif', sa.String(length=2048), nullable=True),
    sa.Column('sequence', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['primer_panels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primers_panel_id'), 'primers', ['panel_id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('name_pattern', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.Enum('negative', 'positive', name='control_kind'), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_kit_id'), 'controls', ['kit_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'staging', 'awaiting_confirmation', 'running', 'rendering', 'uploading', 'succeeded', 'failed', name='job_status'), nullable=False),
    sa.Column('fastq_source', sa.Enum('upload', 'server', 'link', name='fastq_source'), nullable=False),
    sa.Column('fastq1_ref', sa.String(length=1024), nullable=True),
    sa.Column('fastq2_ref', sa.String(length=1024), nullable=True),
    sa.Column('min_identity', sa.Float(), nullable=False),
    sa.Column('min_overlap', sa.Integer(), nullable=False),
    sa.Column('expected_read_number', sa.BigInteger(), nullable=True),
    sa.Column('observed_read_count', sa.BigInteger(), nullable=True),
    sa.Column('reads_confirmed', sa.Boolean(), nullable=False),
    sa.Column('storage_prefix', sa.String(length=512), nullable=True),
    sa.Column('nextflow_run_name', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kit_id'), 'jobs', ['kit_id'], unique=False)
    op.create_index(op.f('ix_jobs_public_id'), 'jobs', ['public_id'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('kit_access',
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('kit_id', 'user_id')
    )
    op.create_table('tag_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_columns_kit_id'), 'tag_columns', ['kit_id'], unique=False)
    op.create_table('result_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('genotypes', 'positions', 'frequency', 'consensus', 'reads_summary', 'html_report', 'consensus_report', 'ngsfilter', name='result_kind'), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_files_job_id'), 'result_files', ['job_id'], unique=False)
    op.create_table('sample_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sample_sheet_key', sa.String(length=512), nullable=True),
    sa.Column('sample_names_text', sa.String(length=65536), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=True),
    sa.Column('selected_tags', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_batches_job_id'), 'sample_batches', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_batches_job_id'), table_name='sample_batches')
    op.drop_table('sample_batches')
    op.drop_index(op.f('ix_result_files_job_id'), table_name='result_files')
    op.drop_table('result_files')
    op.drop_index(op.f('ix_tag_columns_kit_id'), table_name='tag_columns')
    op.drop_table('tag_columns')
    op.drop_table('kit_access')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_public_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kit_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_controls_kit_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_primers_panel_id'), table_name='primers')
    op.drop_table('primers')
    op.drop_index(op.f('ix_kits_kit_code'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tag_layouts')
    op.drop_index(op.f('ix_primer_panels_code'), table_name='primer_panels')
    op.drop_table('primer_panels')
    # ### end Alembic commands ###
