"""projects_and_matching

Revision ID: 8e21237a1d0b
Revises: 3092300d6a45
Create Date: 2026-07-14 19:09:25.012545
"""
from alembic import op
import sqlalchemy as sa


revision = '8e21237a1d0b'
down_revision = '3092300d6a45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Autogenerate does NOT diff enum *values*: add the new result_kind member by hand.
    # ADD VALUE cannot run in a transaction on older PG, so use an autocommit block.
    if op.get_bind().dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE result_kind ADD VALUE IF NOT EXISTS 'reference_alleles'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organisation', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_project_owner_name')
    )
    op.create_index(op.f('ix_projects_owner_user_id'), 'projects', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.create_table('populations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_population_project_name')
    )
    op.create_index(op.f('ix_populations_project_id'), 'populations', ['project_id'], unique=False)
    op.create_table('project_access',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'editor', name='project_role'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('reference_alleles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.String(length=2048), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('allele_name', sa.String(length=64), nullable=False),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'marker', 'sequence', name='uq_refallele_proj_marker_seq')
    )
    op.create_index('ix_refallele_proj_marker_name', 'reference_alleles', ['project_id', 'marker', 'allele_name'], unique=False)
    op.create_index(op.f('ix_reference_alleles_project_id'), 'reference_alleles', ['project_id'], unique=False)
    op.create_table('sample_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('exclude_from_analysis', sa.Boolean(), nullable=False),
    sa.Column('reliable_sample_type', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uq_sampletype_project_code')
    )
    op.create_index(op.f('ix_sample_types_project_id'), 'sample_types', ['project_id'], unique=False)
    op.create_table('matching_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pi_max', sa.Float(), nullable=False),
    sa.Column('pisib_max', sa.Float(), nullable=False),
    sa.Column('max_ado_mm_match', sa.Integer(), nullable=False),
    sa.Column('max_1ic_match', sa.Integer(), nullable=False),
    sa.Column('max_2ic_match', sa.Integer(), nullable=False),
    sa.Column('max_total_mm_match', sa.Integer(), nullable=False),
    sa.Column('reliable_pi_max', sa.Float(), nullable=False),
    sa.Column('reliable_pisib_max', sa.Float(), nullable=False),
    sa.Column('reliable_max_ado_mm', sa.Integer(), nullable=False),
    sa.Column('reliable_max_1ic', sa.Integer(), nullable=False),
    sa.Column('reliable_max_2ic', sa.Integer(), nullable=False),
    sa.Column('reliable_max_total', sa.Integer(), nullable=False),
    sa.Column('min_shared_loci', sa.Integer(), nullable=False),
    sa.Column('mismatch_metric', sa.Enum('flat', 'decomposed', name='mismatch_metric'), nullable=False),
    sa.Column('use_pi_gate', sa.Boolean(), nullable=False),
    sa.Column('tm_possible', sa.Integer(), nullable=False),
    sa.Column('tm_reliable', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_settings_project_id'), 'matching_settings', ['project_id'], unique=False)
    op.create_table('population_allele_frequencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('allele_name', sa.String(length=64), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_id', 'marker', 'allele_name', name='uq_popfreq_pop_marker_al')
    )
    op.create_index(op.f('ix_population_allele_frequencies_population_id'), 'population_allele_frequencies', ['population_id'], unique=False)
    op.create_table('population_markers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('n_alleles', sa.Integer(), nullable=True),
    sa.Column('effective_alleles', sa.Float(), nullable=True),
    sa.Column('pi', sa.Float(), nullable=True),
    sa.Column('pi_sib', sa.Float(), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('population_id', 'marker', name='uq_popmarker_pop_marker')
    )
    op.create_index(op.f('ix_population_markers_population_id'), 'population_markers', ['population_id'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('include_in_matching', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_study_project_name')
    )
    op.create_index(op.f('ix_studies_project_id'), 'studies', ['project_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('system_code', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=True),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('sample_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('unknown', 'male', 'female', name='sex'), nullable=False),
    sa.Column('sex_locked', sa.Boolean(), nullable=False),
    sa.Column('discard_sample', sa.Boolean(), nullable=False),
    sa.Column('animal_matchlock', sa.Boolean(), nullable=False),
    sa.Column('is_animal_reference', sa.Boolean(), nullable=False),
    sa.Column('genotype_ok', sa.Boolean(), nullable=False),
    sa.Column('quality_index', sa.Float(), nullable=True),
    sa.Column('n_replicates', sa.Integer(), nullable=True),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_type_id'], ['sample_types.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['subgroup_id'], ['match_subgroups.id'], name='fk_samples_subgroup', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_job_id'), 'samples', ['job_id'], unique=False)
    op.create_index('ix_samples_job_name', 'samples', ['job_id', 'name'], unique=False)
    op.create_index(op.f('ix_samples_population_id'), 'samples', ['population_id'], unique=False)
    op.create_index(op.f('ix_samples_project_id'), 'samples', ['project_id'], unique=False)
    op.create_index(op.f('ix_samples_public_id'), 'samples', ['public_id'], unique=True)
    op.create_index(op.f('ix_samples_subgroup_id'), 'samples', ['subgroup_id'], unique=False)
    op.create_index(op.f('ix_samples_system_code'), 'samples', ['system_code'], unique=True)
    op.create_table('consensus_genotypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('allele1', sa.String(length=64), nullable=True),
    sa.Column('allele2', sa.String(length=64), nullable=True),
    sa.Column('allele3', sa.String(length=64), nullable=True),
    sa.Column('allele4', sa.String(length=64), nullable=True),
    sa.Column('allele1_id', sa.Integer(), nullable=True),
    sa.Column('allele2_id', sa.Integer(), nullable=True),
    sa.Column('allele3_id', sa.Integer(), nullable=True),
    sa.Column('allele4_id', sa.Integer(), nullable=True),
    sa.Column('ncnf_a1', sa.Integer(), nullable=True),
    sa.Column('ncnf_a2', sa.Integer(), nullable=True),
    sa.Column('confirmed_alleles', sa.String(length=512), nullable=False),
    sa.Column('unconfirmed_alleles', sa.String(length=512), nullable=False),
    sa.Column('n_amp', sa.Integer(), nullable=True),
    sa.Column('n_amp_ok', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('ado', sa.Integer(), nullable=True),
    sa.Column('ado_rate', sa.Float(), nullable=True),
    sa.Column('quality_index', sa.Float(), nullable=True),
    sa.Column('false_alleles', sa.Integer(), nullable=True),
    sa.Column('reads_per_amp', sa.Integer(), nullable=True),
    sa.Column('sd_reads_per_amp', sa.Float(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('pipeline', 'recomputed', 'manual', name='consensus_source'), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['allele1_id'], ['reference_alleles.id'], ),
    sa.ForeignKeyConstraint(['allele2_id'], ['reference_alleles.id'], ),
    sa.ForeignKeyConstraint(['allele3_id'], ['reference_alleles.id'], ),
    sa.ForeignKeyConstraint(['allele4_id'], ['reference_alleles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'marker', name='uq_consensus_sample_marker')
    )
    op.create_index(op.f('ix_consensus_genotypes_sample_id'), 'consensus_genotypes', ['sample_id'], unique=False)
    op.create_table('matching_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='run_status'), nullable=False),
    sa.Column('mode', sa.Enum('reference_anchored', 'clique', name='matching_mode'), nullable=False),
    sa.Column('settings_snapshot', sa.JSON(), nullable=True),
    sa.Column('incremental', sa.Boolean(), nullable=False),
    sa.Column('single_sample_id', sa.Integer(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('n_matches', sa.Integer(), nullable=True),
    sa.Column('n_subgroups', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['single_sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_runs_population_id'), 'matching_runs', ['population_id'], unique=False)
    op.create_index(op.f('ix_matching_runs_public_id'), 'matching_runs', ['public_id'], unique=True)
    op.create_table('replicate_amplifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('plate', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('tag_combo', sa.String(length=128), nullable=True),
    sa.Column('run_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_replamp_sample_marker', 'replicate_amplifications', ['sample_id', 'marker'], unique=False)
    op.create_index(op.f('ix_replicate_amplifications_sample_id'), 'replicate_amplifications', ['sample_id'], unique=False)
    op.create_table('replicate_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=128), nullable=False),
    sa.Column('plate', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('tag_combo', sa.String(length=128), nullable=True),
    sa.Column('run_name', sa.String(length=128), nullable=True),
    sa.Column('read_count', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('called', sa.Boolean(), nullable=False),
    sa.Column('flag', sa.String(length=32), nullable=False),
    sa.Column('stutter', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.String(length=2048), nullable=True),
    sa.Column('allele_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replicate_observations_sample_id'), 'replicate_observations', ['sample_id'], unique=False)
    op.create_index('ix_replobs_sample_marker', 'replicate_observations', ['sample_id', 'marker'], unique=False)
    op.create_table('consensus_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consensus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=512), nullable=True),
    sa.Column('new_value', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consensus_id'], ['consensus_genotypes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_edit_log_consensus_id'), 'consensus_edit_log', ['consensus_id'], unique=False)
    op.create_table('match_subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('reference_sample_id', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('sex', sa.Enum('unknown', 'male', 'female', name='sex'), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['matching_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_subgroups_population_id'), 'match_subgroups', ['population_id'], unique=False)
    op.create_index(op.f('ix_match_subgroups_public_id'), 'match_subgroups', ['public_id'], unique=True)
    op.create_table('match_supergroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['matching_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_supergroups_population_id'), 'match_supergroups', ['population_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.Column('sample_a_id', sa.Integer(), nullable=False),
    sa.Column('sample_b_id', sa.Integer(), nullable=False),
    sa.Column('loci_matched', sa.Integer(), nullable=True),
    sa.Column('loci_compared', sa.Integer(), nullable=True),
    sa.Column('num_ado_mm', sa.Integer(), nullable=True),
    sa.Column('num_1ic', sa.Integer(), nullable=True),
    sa.Column('num_2ic', sa.Integer(), nullable=True),
    sa.Column('num_total_ic', sa.Integer(), nullable=True),
    sa.Column('flat_mismatch', sa.Integer(), nullable=True),
    sa.Column('d_pi', sa.Float(), nullable=True),
    sa.Column('d_pi_sib', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('none', 'possible', 'reliable', name='match_tier'), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['populations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['matching_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_a_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['sample_b_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sample_a_id', 'sample_b_id', name='uq_match_run_pair')
    )
    op.create_index(op.f('ix_matches_population_id'), 'matches', ['population_id'], unique=False)
    op.create_index(op.f('ix_matches_run_id'), 'matches', ['run_id'], unique=False)
    op.create_index(op.f('ix_matches_sample_a_id'), 'matches', ['sample_a_id'], unique=False)
    op.create_index(op.f('ix_matches_sample_b_id'), 'matches', ['sample_b_id'], unique=False)
    op.create_table('matching_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['matching_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_log_run_id'), 'matching_log', ['run_id'], unique=False)
    op.create_table('match_supergroup_members',
    sa.Column('supergroup_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subgroup_id'], ['match_subgroups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supergroup_id'], ['match_supergroups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('supergroup_id', 'subgroup_id')
    )
    op.add_column('jobs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('default_population_id', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('default_study_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_foreign_key('fk_jobs_project', 'jobs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('fk_jobs_default_population', 'jobs', 'populations',
                          ['default_population_id'], ['id'])
    op.create_foreign_key('fk_jobs_default_study', 'jobs', 'studies',
                          ['default_study_id'], ['id'])
    # ### end Alembic commands ###
    # The samples->match_subgroups FK is use_alter (circular with match_subgroups.reference_sample_id)
    # and is skipped by create_table, so add it explicitly now that both tables exist.
    op.create_foreign_key('fk_samples_subgroup', 'samples', 'match_subgroups',
                          ['subgroup_id'], ['id'], use_alter=True)


def downgrade() -> None:
    # Drop the use_alter FK first so the circular dependency doesn't block table drops.
    op.drop_constraint('fk_samples_subgroup', 'samples', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_default_study', 'jobs', type_='foreignkey')
    op.drop_constraint('fk_jobs_default_population', 'jobs', type_='foreignkey')
    op.drop_constraint('fk_jobs_project', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_column('jobs', 'default_study_id')
    op.drop_column('jobs', 'default_population_id')
    op.drop_column('jobs', 'project_id')
    op.drop_table('match_supergroup_members')
    op.drop_index(op.f('ix_matching_log_run_id'), table_name='matching_log')
    op.drop_table('matching_log')
    op.drop_index(op.f('ix_matches_sample_b_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_sample_a_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_run_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_population_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_match_supergroups_population_id'), table_name='match_supergroups')
    op.drop_table('match_supergroups')
    op.drop_index(op.f('ix_match_subgroups_public_id'), table_name='match_subgroups')
    op.drop_index(op.f('ix_match_subgroups_population_id'), table_name='match_subgroups')
    op.drop_table('match_subgroups')
    op.drop_index(op.f('ix_consensus_edit_log_consensus_id'), table_name='consensus_edit_log')
    op.drop_table('consensus_edit_log')
    op.drop_index('ix_replobs_sample_marker', table_name='replicate_observations')
    op.drop_index(op.f('ix_replicate_observations_sample_id'), table_name='replicate_observations')
    op.drop_table('replicate_observations')
    op.drop_index(op.f('ix_replicate_amplifications_sample_id'), table_name='replicate_amplifications')
    op.drop_index('ix_replamp_sample_marker', table_name='replicate_amplifications')
    op.drop_table('replicate_amplifications')
    op.drop_index(op.f('ix_matching_runs_public_id'), table_name='matching_runs')
    op.drop_index(op.f('ix_matching_runs_population_id'), table_name='matching_runs')
    op.drop_table('matching_runs')
    op.drop_index(op.f('ix_consensus_genotypes_sample_id'), table_name='consensus_genotypes')
    op.drop_table('consensus_genotypes')
    op.drop_index(op.f('ix_samples_system_code'), table_name='samples')
    op.drop_index(op.f('ix_samples_subgroup_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_public_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_project_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_population_id'), table_name='samples')
    op.drop_index('ix_samples_job_name', table_name='samples')
    op.drop_index(op.f('ix_samples_job_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_studies_project_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_population_markers_population_id'), table_name='population_markers')
    op.drop_table('population_markers')
    op.drop_index(op.f('ix_population_allele_frequencies_population_id'), table_name='population_allele_frequencies')
    op.drop_table('population_allele_frequencies')
    op.drop_index(op.f('ix_matching_settings_project_id'), table_name='matching_settings')
    op.drop_table('matching_settings')
    op.drop_index(op.f('ix_sample_types_project_id'), table_name='sample_types')
    op.drop_table('sample_types')
    op.drop_index(op.f('ix_reference_alleles_project_id'), table_name='reference_alleles')
    op.drop_index('ix_refallele_proj_marker_name', table_name='reference_alleles')
    op.drop_table('reference_alleles')
    op.drop_table('project_access')
    op.drop_index(op.f('ix_populations_project_id'), table_name='populations')
    op.drop_table('populations')
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
    # Autogenerate leaves the native enum TYPES behind after dropping their tables, which breaks a
    # later re-upgrade (CREATE TYPE collision). Drop them so downgrade->upgrade cycles are clean.
    # (result_kind is left intact — it predates this migration; the added value stays, harmless.)
    if op.get_bind().dialect.name == "postgresql":
        for t in ("sex", "project_role", "consensus_source", "match_tier",
                  "run_status", "mismatch_metric", "matching_mode"):
            op.execute(f"DROP TYPE IF EXISTS {t}")
